remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
title: evanisnor.com
logo: /assets/images/evan.jpg
description: <h2>Evan Isnor</h2><p>Nova Scotia, Canada 🇨🇦</p><p>Professional Software Engineer since 2009</p>